version: '3'
services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: react-chat-backend
    ports:
      - '3000:3000'
    volumes:
      - ..:/app
      - /app/node_modules # Avoid overwriting the node_modules folder inside the container
    environment:
      NODE_ENV: development
    command:
      - npm
      - run
      - watch
